######################################################################
#  Project
######################################################################

BINARY		= ultimate-midi
SRCFILES	= ultimate-midi.c

all: elf bin

include ../Makefile.incl

# End
